server:
  port: 8081
  servlet:
    context-path: /his
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hisdb
    username: root
    password: 123456
  # swagger的配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
logging:
  level:
    cn.neusoft: debug
#mybatisplus 会将字段 businessName转换成business_name 关闭这个转换
mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
  type-aliases-package: org.example.pojo
#  mapper-locations: classpath:mapper/*Mapper.xml

# 自定义
uploadlocation: "D:/upload1118/"
serverpath: "http://localhost:${server.port}${server.servlet.context-path}"
alloworigins: http://localhost:9001